#![cfg(all(feature = "serialize", feature = "deserialize"))]
use rstest::rstest;
use serde::{Deserialize, Serialize};
use std::collections::BTreeMap;

#[test]
fn test_enum_struct_1() -> anyhow::Result<()> {
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    pub struct Foo {
        foo: Bar,
    }

    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    pub enum Bar {
        Bar(i32),
    }

    let yaml = serde_saphyr::to_string(&vec![Foo { foo: Bar::Bar(2) }])?;
    let foo: Vec<Foo> = serde_saphyr::from_str(yaml.as_str())?;
    assert_eq!(foo.first().expect("empty vector?").foo, Bar::Bar(2));
    Ok(())
}

#[test]
fn test_enum_struct_2() -> anyhow::Result<()> {
    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    pub struct Outer {
        inner: Vec<Inner>,
    }

    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    pub struct Inner {
        foo: Foo,
    }

    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    pub enum Foo {
        Bar(Bar),
    }

    #[derive(Serialize, Deserialize, Debug, PartialEq)]
    pub enum Bar {
        Baz(i32),
    }

    let value = Outer {
        inner: vec![Inner {
            foo: Foo::Bar(Bar::Baz(42)),
        }],
    };
    let yaml = serde_saphyr::to_string(&value)?;

    let r: Outer = serde_saphyr::from_str(&yaml)?;
    assert_eq!(value, r);

    Ok(())
}

#[test]
fn tuple_variant_round_trips_when_nested_under_a_key() -> anyhow::Result<()> {
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    enum E {
        Tup(u8, u8, u8),
    }

    let value = BTreeMap::from([(
        "hello".to_string(),
        BTreeMap::from([("world".to_string(), E::Tup(1, 2, 3))]),
    )]);
    let yaml = serde_saphyr::to_string(&value)?;
    let r: BTreeMap<String, BTreeMap<String, E>> = serde_saphyr::from_str(&yaml)?;
    assert_eq!(value, r);

    Ok(())
}

#[derive(Serialize, Deserialize, PartialEq, Debug)]
enum ComplexFieldEnum {
    Tup(Box<ComplexFieldEnum>, Box<ComplexFieldEnum>),
    Strukt { field: Box<ComplexFieldEnum> },
    EmptyStrukt {},
    EmptyTup(),
    Seq(Vec<ComplexFieldEnum>),
    Unit,
}

/// A tuple-variant whose first field is itself a complex node (a struct variant,
/// a sequence, another tuple variant). Each field must keep its body indented
/// under its own dash rather than dedenting to the dash column.
#[rstest]
#[case::struct_variant(ComplexFieldEnum::Strukt {
    field: Box::new(ComplexFieldEnum::Unit),
})]
#[case::sequence(ComplexFieldEnum::Seq(vec![ComplexFieldEnum::Unit]))]
#[case::tuple_variant(ComplexFieldEnum::Tup(
    Box::new(ComplexFieldEnum::Unit),
    Box::new(ComplexFieldEnum::Unit),
))]
#[case::empty_struct_variant(ComplexFieldEnum::EmptyStrukt {})]
#[case::empty_tuple_variant(ComplexFieldEnum::EmptyTup())]
fn tuple_variant_round_trips_with_complex_fields(
    #[case] first_field: ComplexFieldEnum,
    #[values(1, 2, 4)] indent_step: usize,
    #[values(false, true)] compact_list_indent: bool,
) -> anyhow::Result<()> {
    let value = ComplexFieldEnum::Tup(Box::new(first_field), Box::new(ComplexFieldEnum::Unit));
    let opts = serde_saphyr::ser_options! {
        indent_step: indent_step,
        compact_list_indent: compact_list_indent,
    };
    let yaml = serde_saphyr::to_string_with_options(&value, opts.clone())?;
    let r: ComplexFieldEnum =
        serde_saphyr::from_str(&yaml).map_err(|e| anyhow::anyhow!("{e}\n--- yaml ---\n{yaml}"))?;
    assert_eq!(value, r, "round-trip mismatch for:\n{yaml}");
    assert_eq!(yaml, serde_saphyr::to_string_with_options(&r, opts)?);

    Ok(())
}

/// The recursive enum shape generated by the serializer fuzz target's retained
/// `fuzz/reproducers/serialize_enum_indent.hex` input (`1c65`) and the minimized
/// `F%%` input from crash-c22b1997aa76cea333b69ac9e77d1e4a3a5d6e69.
#[derive(Serialize, Deserialize, PartialEq, Debug)]
#[serde(rename = "Node")]
enum FuzzIndentNode {
    Null,
    Int(i64),
    EnumTuple(Box<FuzzIndentNode>, Box<FuzzIndentNode>),
    EnumStruct { field: Box<FuzzIndentNode> },
    Seq(Vec<FuzzIndentNode>),
}

#[rstest]
#[case::minimized_sequence(
    FuzzIndentNode::Seq(vec![
        FuzzIndentNode::EnumStruct { field: Box::new(FuzzIndentNode::Null) },
        FuzzIndentNode::Null,
    ]),
    false,
    false,
)]
#[case::retained_tuple(
    FuzzIndentNode::EnumTuple(
        Box::new(FuzzIndentNode::EnumStruct { field: Box::new(FuzzIndentNode::Null) }),
        Box::new(FuzzIndentNode::Null),
    ),
    true,
    true,
)]
// The original crash's first sequence item had a tuple around the struct and
// this integer field; preserve that additional level of nesting as well.
#[case::original_nested_tuple(
    FuzzIndentNode::Seq(vec![
        FuzzIndentNode::EnumTuple(
            Box::new(FuzzIndentNode::EnumStruct {
                field: Box::new(FuzzIndentNode::Int(5_134_477_568_241_976_902)),
            }),
            Box::new(FuzzIndentNode::Null),
        ),
        FuzzIndentNode::Null,
    ]),
    false,
    false,
)]
fn fuzz_enum_indentation_round_trips(
    #[case] value: FuzzIndentNode,
    #[case] tagged_enums: bool,
    #[case] yaml_12: bool,
) -> anyhow::Result<()> {
    let opts = serde_saphyr::ser_options! {
        indent_step: 1,
        compact_list_indent: false,
        quote_all: true,
        tagged_enums: tagged_enums,
        yaml_12: yaml_12,
    };
    let yaml = serde_saphyr::to_string_with_options(&value, opts.clone())?;
    let back: FuzzIndentNode =
        serde_saphyr::from_str(&yaml).map_err(|e| anyhow::anyhow!("{e}\n--- yaml ---\n{yaml}"))?;
    assert_eq!(value, back, "round-trip mismatch for:\n{yaml}");
    assert_eq!(yaml, serde_saphyr::to_string_with_options(&back, opts)?);

    Ok(())
}

#[rstest]
#[case::after_block_seq(ComplexFieldEnum::Seq(vec![
    ComplexFieldEnum::Unit,
    ComplexFieldEnum::Unit,
]))]
#[case::after_nested_tuple(ComplexFieldEnum::Tup(
    Box::new(ComplexFieldEnum::Unit),
    Box::new(ComplexFieldEnum::Unit),
))]
fn empty_tuple_field_after_block_sibling_round_trips(
    #[case] block_first_field: ComplexFieldEnum,
) -> anyhow::Result<()> {
    let value = ComplexFieldEnum::Tup(
        Box::new(block_first_field),
        Box::new(ComplexFieldEnum::Seq(vec![])),
    );
    let yaml = serde_saphyr::to_string(&value)?;
    let r: ComplexFieldEnum = serde_saphyr::from_str(&yaml).unwrap();
    assert_eq!(value, r, "round-trip mismatch for:\n{yaml}");

    Ok(())
}

#[test]
fn struct_variant_round_trips_when_nested_under_a_key() -> anyhow::Result<()> {
    #[derive(Serialize, Deserialize, PartialEq, Debug)]
    enum E {
        Strukt { a: u8, b: u8 },
    }

    let value = BTreeMap::from([(
        "hello".to_string(),
        BTreeMap::from([("world".to_string(), E::Strukt { a: 1, b: 2 })]),
    )]);
    let yaml = serde_saphyr::to_string(&value)?;
    let r: BTreeMap<String, BTreeMap<String, E>> = serde_saphyr::from_str(&yaml)?;
    assert_eq!(value, r);

    Ok(())
}
